services:
  caddy:
    container_name: "arma3sync-repo"
    image: "caddy:2.10"
    pull_policy: "always"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "arma3sync-repo:/srv:ro"
      - "./browse.html:/etc/caddy/templates/browse.html:ro"
      # Long syntax is needed because of https://github.com/docker/compose/issues/12993
      - type: "volume"
        source: "mod-staging-directory"
        target: "${MOUNT_PATH_MOD_STAGING:?error}"
        read_only: true
        volume:
          nocopy: true
      - type: "volume"
        source: "local-mods-directory"
        target: "${MOUNT_PATH_LOCAL_MODS:?error}"
        read_only: true
        volume:
          nocopy: true
    configs:
      - source: "caddy-config"
        target: "/etc/caddy/Caddyfile"
    networks:
      - "proxy"
    labels:
      traefik.enable: true
      traefik.http.routers.arma3sync-repo.entrypoints: "websecure-internal,websecure-external"
      traefik.http.routers.arma3sync-repo.rule: "Host(`mods-test.${TRAEFIK_DOMAINNAME_1:?error}`)"
      traefik.http.routers.arma3sync-repo.service: "arma3sync-repo"
      traefik.http.services.arma3sync-repo.loadbalancer.server.port: 80
volumes:
  arma3sync-repo:
    driver: "local"
    driver_opts:
      type: "cifs"
      o: "username=${SMB_USERNAME:?error},password=${SMB_PASSWORD:?error},rw,noperm,file_mode=0777,dir_mode=0777"
      device: "//${SMB_HOST:?error}/${SMB_PATH_REPO:?error}"
  mod-staging-directory:
    driver: "local"
    driver_opts:
      type: "cifs"
      o: "username=${SMB_USERNAME:?error},password=${SMB_PASSWORD:?error},rw,noperm,file_mode=0777,dir_mode=0777"
      device: "//${SMB_HOST:?error}/${SMB_PATH_MOD_STAGING:?error}"
  local-mods-directory:
    driver: "local"
    driver_opts:
      type: "cifs"
      o: "username=${SMB_USERNAME:?error},password=${SMB_PASSWORD:?error},rw,noperm,file_mode=0777,dir_mode=0777"
      device: "//${SMB_HOST:?error}/${SMB_PATH_LOCAL_MODS:?error}"
configs:
  caddy-config:
    content: |
      :80 {
        root * /srv
        file_server browse {
          template /etc/caddy/templates/browse.html
        }
      }
networks:
  proxy:
    external: true
    name: "${TRAEFIK_NETWORK_NAME:-proxy}"