services:
  influxdb2:
    container_name: "${COMPOSE_PROJECT_NAME:?error}-influxdb2"
    image: "influxdb:2.9.1"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "8086:8086"
    networks:
      - "grafana"
      - "proxy"
    volumes:
      - "${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/influxdb2-data:/var/lib/influxdb2:z"
      - "${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/influxdb2-config:/etc/influxdb2:z"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_ORG: "tactical-training-team"
      DOCKER_INFLUXDB_INIT_BUCKET: "tactical-training-team"
      DOCKER_INFLUXDB_INIT_USERNAME: "${ADMIN_USERNAME:?error}"
      DOCKER_INFLUXDB_INIT_PASSWORD: "${ADMIN_PASSWORD:?error}"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "${ADMIN_TOKEN:?error}"
    labels:
      traefik.enable: true
      traefik.http.routers.ifxmetrics.entrypoints: "websecure-internal"
      traefik.http.routers.ifxmetrics.rule: "Host(`ifxmetrics.${TRAEFIK_DOMAINNAME_1:?error}`)"
      traefik.http.routers.ifxmetrics.service: "ifxmetrics"
      # traefik.http.routers.grafana.middlewares: "authentik"
      traefik.http.services.ifxmetrics.loadbalancer.server.port: 8086
networks:
  grafana:
    external: true
    name: "grafana"
  proxy:
    external: true
    name: "proxy"