services:
  beszel:
    image: "henrygd/beszel:0.18.7"
    container_name: "${COMPOSE_PROJECT_NAME:?error}"
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    environment:
      TZ: "${TZ:-Europe/Berlin}"
    volumes:
      - "${DOCKER_DATA_DIR:?error}/${COMPOSE_PROJECT_NAME:?error}/data:/beszel_data:z"
    ports:
      - "10090:8090"
    networks:
      proxy:
    labels:
      traefik.enable: true
      traefik.http.routers.beszel.entrypoints: "websecure-internal"
      traefik.http.routers.beszel.rule: "Host(`monitoring.${TRAEFIK_DOMAINNAME_1:?error}`)"
      traefik.http.routers.beszel.service: "beszel"
      traefik.http.services.beszel.loadbalancer.server.port: 8090

networks:
  proxy:
    external: true
    name: "${TRAEFIK_NETWORK_NAME:-proxy}"