services:
  website:
    container_name: "${COMPOSE_PROJECT_NAME:?error}"
    build: "https://github.com/TacticalTrainingTeam/ttt-frontend.git"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - "ALL"
    cap_add:
      - "NET_BIND_SERVICE"
    environment:
      TZ: "Europe/Berlin"
    networks:
      - "proxy"
    labels:
      traefik.enable: true
      traefik.http.routers.website-staging.entrypoints: "websecure-internal,websecure-external"
      traefik.http.routers.website-staging.rule: "Host(`staging.${TRAEFIK_DOMAINNAME_1:?error}`)"
      traefik.http.routers.website-staging.service: "website-staging"
      traefik.http.services.website-staging.loadbalancer.server.port: 80
networks:
  proxy:
    external: true
    name: "proxy"