services:
  caddy:
    container_name: "missions"
    image: "caddy:2.10"
    pull_policy: "always"
    restart: "unless-stopped"
    security_opt:
      - "no-new-privileges:true"
    volumes:
      - "missions:/srv/mpmissions:ro"
      - "missions-archive:/srv/mpmissions-archiv:ro"
    configs:
      - source: "caddy-config"
        target: "/etc/caddy/Caddyfile"
    networks:
      - "proxy"
    labels:
      traefik.enable: true
      traefik.http.routers.missions.entrypoints: "websecure-internal,websecure-external"
      traefik.http.routers.missions.rule: "Host(`missions.${TRAEFIK_DOMAINNAME_1:?error}`)"
      traefik.http.routers.missions.service: "missions"
      traefik.http.services.missions.loadbalancer.server.port: 80
volumes:
  missions:
    driver: "local"
    driver_opts:
      type: "cifs"
      o: "username=${SMB_USERNAME:?error},password=${SMB_PASSWORD:?error},rw,noperm,file_mode=0777,dir_mode=0777"
      device: "//${SMB_HOST:?error}/${SMB_PATH_MISSIONS:?error}"
  missions-archive:
    driver: "local"
    driver_opts:
      type: "cifs"
      o: "username=${SMB_USERNAME:?error},password=${SMB_PASSWORD:?error},rw,noperm,file_mode=0777,dir_mode=0777"
      device: "//${SMB_HOST:?error}/${SMB_PATH_MISSIONS_ARCHIVE:?error}"
configs:
  caddy-config:
    content: |
      :80 {
        root * /srv
        file_server {
          browse /templates/browse.html
        }
      }
networks:
  proxy:
    external: true
    name: "${TRAEFIK_NETWORK_NAME:-proxy}"